[package]
name = "weather"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "weather.rs"

[dependencies]
reqwest.workspace = true
anyhow.workspace = true
url.workspace = true
serde.workspace = true
